import type { Product } from '../lib/types/product';

export const mockProducts: Product[] = [
  // 👕 Men's T-Shirts (6)
  {
    _id: 'p1',
    name: 'Classic White T-Shirt',
    image: '../assets/image/product/t-shirt-1.png',
    images: [
      'https://picsum.photos/seed/mens-classic-white-tshirt-1/600/800',
      'https://picsum.photos/seed/mens-classic-white-tshirt-2/600/800',
    ],
    price: 25,
    discountedAmount: 10,
    category: 'Men',
    description:
      'A comfortable classic white cotton t-shirt for everyday wear.',
    size: ['S', 'M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.3,
      numOfReviews: 12,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 30,
  },
  {
    _id: 'p2',
    name: 'Black Graphic Tee',
    image: '../assets/image/product/t-shirt-2.png',
    images: [
      'https://picsum.photos/seed/mens-black-graphic-tee-1/600/800',
      'https://picsum.photos/seed/mens-black-graphic-tee-2/600/800',
    ],
    price: 30,
    discountedAmount: 10,
    category: 'Men',
    description: 'Trendy black t-shirt with a stylish graphic print.',
    size: ['M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.6,
      numOfReviews: 8,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 20,
  },
  {
    _id: 'p3',
    name: 'Blue Round Neck T-Shirt',
    image: '../assets/image/product/t-shirt-3.png',
    images: [
      'https://picsum.photos/seed/mens-blue-round-neck-1/600/800',
      'https://picsum.photos/seed/mens-blue-round-neck-2/600/800',
    ],
    price: 28,
    category: 'Men',
    description: 'Soft blue t-shirt with round neck and short sleeves.',
    size: ['S', 'M', 'L'],
    reviewData: {
      avgRating: 4.1,
      numOfReviews: 10,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 25,
  },
  {
    _id: 'p4',
    name: 'Striped Polo Shirt',
    image: '../assets/image/product/t-shirt-4.png',
    images: ['https://picsum.photos/seed/mens-striped-polo-1/600/800'],
    price: 35,
    discountedAmount: 10,
    category: 'Men',
    description: 'Casual striped polo t-shirt perfect for outings.',
    size: ['M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.7,
      numOfReviews: 15,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 18,
  },
  {
    _id: 'p5',
    name: 'Grey Sports T-Shirt',
    image: '../assets/image/product/t-shirt-5.png',
    images: ['https://picsum.photos/seed/mens-grey-sports-1/600/800'],
    price: 32,
    category: 'Men',
    description: 'Lightweight grey sports t-shirt for gym and running.',
    size: ['S', 'M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.2,
      numOfReviews: 9,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 22,
  },
  {
    _id: 'p6',
    name: 'Red Casual T-Shirt',
    image: '../assets/image/product/t-shirt-6.png',
    images: ['https://picsum.photos/seed/mens-red-casual-1/600/800'],
    price: 26,
    category: 'Men',
    description: 'Bright red casual t-shirt made with 100% cotton.',
    size: ['M', 'L'],
    reviewData: {
      avgRating: 4.5,
      numOfReviews: 14,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 27,
  },

  // 👗 Women's Fashion (5)
  {
    _id: 'w1',
    name: 'Elegant Evening Dress',
    image: 'https://picsum.photos/seed/womens-evening-dress/600/800',
    images: ['https://picsum.photos/seed/womens-evening-dress-1/600/800'],
    price: 80,
    discountedAmount: 10,
    category: 'Women',
    description: 'An elegant black evening dress for special occasions.',
    size: ['S', 'M', 'L'],
    reviewData: {
      avgRating: 4.8,
      numOfReviews: 20,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 15,
  },
  {
    _id: 'w2',
    name: 'Summer Floral Dress',
    image: 'https://picsum.photos/seed/womens-floral-dress/600/800',
    images: ['https://picsum.photos/seed/womens-floral-dress-1/600/800'],
    price: 55,
    category: 'Women',
    description: 'Beautiful floral print summer dress.',
    size: ['S', 'M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.6,
      numOfReviews: 18,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 12,
  },
  {
    _id: 'w3',
    name: 'Casual White Blouse',
    image: 'https://picsum.photos/seed/womens-white-blouse/600/800',
    images: ['https://picsum.photos/seed/womens-white-blouse-1/600/800'],
    price: 40,
    category: 'Women',
    description: 'A lightweight white blouse for casual wear.',
    size: ['S', 'M', 'L'],
    reviewData: {
      avgRating: 4.3,
      numOfReviews: 7,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 20,
  },
  {
    _id: 'w4',
    name: 'Denim Jacket',
    image: 'https://picsum.photos/seed/womens-denim-jacket/600/800',
    images: ['https://picsum.photos/seed/womens-denim-jacket-1/600/800'],
    price: 70,
    discountedAmount: 10,
    category: 'Women',
    description: 'Trendy blue denim jacket with front pockets.',
    size: ['M', 'L'],
    reviewData: {
      avgRating: 4.9,
      numOfReviews: 25,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 10,
  },
  {
    _id: 'w5',
    name: 'Women’s Casual Top',
    image: 'https://picsum.photos/seed/womens-casual-top/600/800',
    images: ['https://picsum.photos/seed/womens-casual-top-1/600/800'],
    price: 35,
    category: 'Women',
    description: 'Casual top for everyday wear.',
    size: ['S', 'M', 'L', 'XL'],
    reviewData: {
      avgRating: 4.1,
      numOfReviews: 6,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 28,
  },

  // 🧒 Kids Fashion (5)
  {
    _id: 'k1',
    name: 'Kids Summer Dress',
    image: 'https://picsum.photos/seed/kids-summer-dress/600/800',
    images: ['https://picsum.photos/seed/kids-summer-dress-1/600/800'],
    price: 30,
    category: 'Kids',
    description: 'Adorable floral summer dress for kids.',
    size: ['2-3Y', '4-5Y', '6-7Y'],
    reviewData: {
      avgRating: 4.7,
      numOfReviews: 10,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 25,
  },
  {
    _id: 'k2',
    name: 'Boys Graphic Tee',
    image: 'https://picsum.photos/seed/kids-graphic-tee/600/800',
    images: ['https://picsum.photos/seed/kids-graphic-tee-1/600/800'],
    price: 20,
    category: 'Kids',
    description: 'Cool graphic t-shirt for boys.',
    size: ['2-3Y', '4-5Y', '6-7Y'],
    reviewData: {
      avgRating: 4.4,
      numOfReviews: 8,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 30,
  },
  {
    _id: 'k3',
    name: 'Kids Hoodie',
    image: 'https://picsum.photos/seed/kids-hoodie/600/800',
    images: ['https://picsum.photos/seed/kids-hoodie-1/600/800'],
    price: 35,
    category: 'Kids',
    description: 'Warm and soft hoodie for kids.',
    size: ['4-5Y', '6-7Y', '8-9Y'],
    reviewData: {
      avgRating: 4.6,
      numOfReviews: 15,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 18,
  },
  {
    _id: 'k4',
    name: 'Girls Party Dress',
    image: 'https://picsum.photos/seed/kids-party-dress/600/800',
    images: ['https://picsum.photos/seed/kids-party-dress-1/600/800'],
    price: 50,
    category: 'Kids',
    description: 'Charming party dress for little girls.',
    size: ['2-3Y', '4-5Y', '6-7Y'],
    reviewData: {
      avgRating: 4.9,
      numOfReviews: 12,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 14,
  },
  {
    _id: 'k5',
    name: 'Kids Pajama Set',
    image: 'https://picsum.photos/seed/kids-pajama-set/600/800',
    images: ['https://picsum.photos/seed/kids-pajama-set-1/600/800'],
    price: 28,
    category: 'Kids',
    description: 'Comfortable pajama set for kids’ bedtime.',
    size: ['2-3Y', '4-5Y', '6-7Y'],
    reviewData: {
      avgRating: 4.5,
      numOfReviews: 9,
      reviewList: [
        {
          _id: 'r1',
          user: {
            _id: 'u1',
            name: 'John Doe',
            image: 'https://picsum.photos/seed/user-john/100/100',
          },
          rating: 5,
          comment: 'Great quality! Fits perfectly.',
          createdAt: new Date().toISOString(),
        },
        {
          _id: 'r2',
          user: {
            _id: 'u2',
            name: 'Emma Smith',
            image: 'https://picsum.photos/seed/user-emma/100/100',
          },
          rating: 4,
          comment: 'Nice t-shirt but runs a little large.',
          createdAt: new Date().toISOString(),
        },
      ],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 22,
  },
];
